USE [master]
GO

/****** Object:  Database [Frizerski_Salon]    Script Date: 7.2.2022. 15:06:20 ******/
CREATE DATABASE [Frizerski_Salon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Frizerski_Salon', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Frizerski_Salon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Frizerski_Salon_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Frizerski_Salon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Frizerski_Salon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Frizerski_Salon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET ARITHABORT OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Frizerski_Salon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Frizerski_Salon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Frizerski_Salon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Frizerski_Salon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET RECOVERY FULL 
GO

ALTER DATABASE [Frizerski_Salon] SET  MULTI_USER 
GO

ALTER DATABASE [Frizerski_Salon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Frizerski_Salon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Frizerski_Salon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Frizerski_Salon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Frizerski_Salon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Frizerski_Salon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Frizerski_Salon] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Frizerski_Salon] SET  READ_WRITE 
GO

